services:
  - type: web
    name: flask-app
    runtime: docker
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libreoffice
      pip install --upgrade pip
      pip install -r requirements.txt
    buildCommand: ""
    dockerfilePath: Dockerfile
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000

